### ISSUE TITLE
install jessie directly with raspbian-ua-netinstall

### ISSUE THREAD

**Issue by diederikdehaas** [vonbrownie/circuidipity#1]
Saw http://www.circuidipity.com/minimal-raspbian-jessie.html and wanted to tell you that you can install jessie directly by having the following in `installer-config.txt`:
```
release=jessie
```
Saves you a lengthy upgrade step :wink: 

Also applies to http://www.circuidipity.com/run-a-raspberry-pi-2-from-external-usb-storage-using-raspbian.html

**Comment by vonbrownie** [comment]
Hi Diederik... Thanks for pointing that out. I noticed that "release="
option but I wanted to modify sources.list before the dist-upgrade and did
not see any option to do so. Hence, I start with a working install of
wheezy, manually alter sources.list, then proceed with dist-upgrade. Its a
minimal install so not too long to get everything OK.

Anyway its a very nice piece of software and I appreciate the effort that
went into creating it!

On Wed, Jul 22, 2015 at 3:08 PM, Diederik de Haas <notifications@github.com>
wrote:

> Saw http://www.circuidipity.com/minimal-raspbian-jessie.html and wanted
> to tell you that you can install jessie directly by having the following in
> installer-config.txt:
>
> release=jessie
>
> Saves you a lengthy upgrade step [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vonbrownie/circuidipity/issues/1>.
>



-- 
(o<  .: Per curiositas ad astra .: http://www.circuidipity.com
(/)_

**Comment by diederikdehaas** [comment]
> I wanted to modify sources.list before the dist-upgrade and did not see any option to do so

Currently there indeed isn't an option for that (but it's in the works).
But afaics in your examples it wouldn't have an effect and you could therefor also do it in `post-install.txt`. But you're free to use it in any way you like it. Just created the issue to point out another way :smile: 

> Anyway its a very nice piece of software and I appreciate the effort that went into creating it!

Thanks :+1:
